### ISSUE TITLE
downloads fails due to renamed assets

### ISSUE THREAD

**Issue by mortax** [asdf-community/asdf-mlton#7]
the `install` script, as it currently stands, attempts to download https://github.com/MLton/mlton/releases/download/on-20200817-release/mlton-20200817-1.amd64-darwin.gmp-static.tgz via:

```
curl --silent --location --create-dirs --output /Users/jrd/.asdf/installs/mlton/20200817/bin/mlton.tgz https://github.com/MLton/mlton/releases/download/on-20200817-release/mlton-20200817-1.amd64-darwin.gmp-static.tgz
```

unfortunately, the asset is now https://github.com/MLton/mlton/releases/download/on-20200817-release/mlton-20200817-1.amd64-19.6-darwin.gmp-static.tgz per https://github.com/MLton/mlton/releases/:

![Screen Shot 2020-09-24 at 2 41 59 PM](https://user-images.githubusercontent.com/788303/94206208-b8042a00-fe79-11ea-9676-6ab2501e49c4.png)

i fixed this (as a quick test) by doing:

```
29a30,31
>   local special=-19.6
> 
50c52
<     platform="${platform}.gmp-static"
---
>     platform="${platform}${special}.gmp-static"
```

this needs more investigation (let me know how i can help; i'm happy to).

**Comment by smorimoto** [comment]
Indeed, ​would you like to tackle this?

**Comment by mortax** [comment]
sure. i'll take a look.

**Comment by smorimoto** [comment]
Cool, thanks.

**Comment by mortax** [comment]
sorry for the delay.

this is now address by #10. unfortunately, i can't link them. if you can, then this will be closed if the PR gets merged.

**Comment by smorimoto** [comment]
No worries at all! Thanks for worked on this!
